#!/usr/bin/env bash

show_help() {
	cat << EOF
Usage: $0 <filename>
EOF
}

# Check if argument (filename) is provided
if [ -z  "$1" ]; then
	show_help
	exit 1
fi


FILENAME=$1


# Check if file exists
if [ ! -f "$FILENAME" ]; then
	echo "Error: File '$FILENAME' not found"
	exit 1
fi

# Cat file and pipe its output to xclip (clipboard)
cat "$FILENAME" | xclip -selection clipboard
echo "Contents of '$FILENAME' copied to clipboard"
