#!/usr/bin/env bash

PS4='+${LINENO}: '

HERE=false
PARTIAL=false
TARGET_PATH=""

# Help function
show_help() {
	cat << EOF
Usage: finish [OPTIONS]

Rename a specified path of a file or directory by appending "_COMPLETED"

Options:
	--here                Marks the current working directory as completed
	--partial             Marks the current working directory as partially completed
	-p, --path PATH       Specify a file or directory's path to mark is as COMPLETED
	-h, --help            Show this help message and exit


Examples:
	finish --here                             Completes current directory
	finish --partial													Partially completes current directory
	finish -p /path/to/directory-or-file      Completes specified directory or file
EOF
echo
}

# Function for error display and exit
error_exit() {
	echo "Error: $1" >&2
	echo "Use 'finish --help' for more information." >&2
	exit 1
}

# The function that renames path or current working directory
rename_path() {
	local original_path="$1"
	local base=""
	local new_path=""
	local suffix=""

	if ! "$PARTIAL"; then
		suffix="_COMPLETED"
	else
		suffix="_PARTIALLY_COMPLETED"
	fi

	# If 'original_path' has an underscore
	if [[ "$original_path" == *_* ]]; then
		base="${original_path%%_*}"   # removes the nearest underscore
		new_path="${base}${suffix}"
	else
		new_path="${original_path}${suffix}"
	fi

	if [[ ! -e "$original_path" ]]; then
		error_exit "Path '$original_path' does not exist"
	fi

	if mv "$original_path" "$new_path"; then
		echo "Successfully renamed '$original_path' to '$new_path'"
		echo
	else
		error_exit "Failed to rename '$original_path'"
	fi
}



# Parse command line arguments
while [[ "$#" -gt 0 ]]; do

	case $1 in 
		-p|--path)
			if [[ -n "$2" && "$2" != -* ]]; then
				TARGET_PATH="$2"
				shift 2
			else
				error_exit "The --path option requires an argument"
			fi
			;;

		--here)
			HERE=true
			shift
			;;

		--partial)
			PARTIAL=true
			shift
			;;

		-h|--help)
			show_help
			exit 0
			;;

		*)
			error_exit "Unknown option: $1"
			;;

	esac
done


# Main
if "$HERE"; then
	if [[ -n "$TARGET_PATH" ]]; then
		error_exit "Cannot use both '--here' and '-p/--path' options together"
	fi
	TARGET_PATH="$(pwd)"
fi

if "$PARTIAL"; then
	if [[ -n "$TARGET_PATH" ]]; then
		error_exit "Cannot use both '--partial' and '-p/--path' options together"
	fi
	TARGET_PATH="$(pwd)"
fi

# If no arguments provided
if [[ "$#" -eq 0 && -z "$TARGET_PATH" ]]; then
	show_help
	exit 0
fi

# If empty TARGET_PATH
if [[ -z "$TARGET_PATH" ]]; then
	error_exit "No target directory or file specified. Use --here or -p/--path to specify what to finish"
fi

# Perform rename
rename_path "$TARGET_PATH"
